In [4]:
# !pip install tensorflow keras

In [3]:
import tensorflow as tf
print(tf.__version__)

2.9.1


In [24]:
# Constant tensors

In [25]:
vector = tf.constant([[1,2],[3,4]], dtype=float)

In [26]:
vector

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [28]:
# Variable Tensors

In [29]:
variable_tensor = tf.Variable([10,7])
non_variable_tensor = tf.constant([10,7])

In [30]:
variable_tensor[0].assign(999)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([999,   7])>

In [31]:
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([999,   7])>

In [33]:
# Random Tensors

In [40]:
random_tensor = tf.random.Generator.from_seed(42)
random_tensor = random_tensor.normal(shape=(2,2))

In [41]:
random_tensor.numpy()

array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)

In [42]:
# Uniform Tensors

In [45]:
not_shuffled_tensor = tf.constant([[10,7,8,9],[2,3,4,5]])

In [50]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled_tensor, seed=42) # operation level random seed

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 2,  3,  4,  5],
       [10,  7,  8,  9]])>

In [53]:
# Tensor creations

In [55]:
tf.ones(shape=(5,3))

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [56]:
tf.zeros(shape=(5,2))

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [57]:
import numpy as np

In [58]:
numpyA = np.arange(1,25, dtype=np.int32)
tf.constant(numpyA)

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [60]:
x = tf.constant(numpyA, shape=(3,8))

In [62]:
x.shape

TensorShape([3, 8])

In [66]:
x.ndim

2

In [68]:
tf.size(x) #number of elements along our tensor

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [69]:
# Indexing and expanding tensors

In [72]:
x

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])>

In [70]:
x[2]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([17, 18, 19, 20, 21, 22, 23, 24])>

In [71]:
x[0:,1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2, 10, 18])>

In [75]:
x[1,7]

<tf.Tensor: shape=(), dtype=int32, numpy=16>

In [76]:
x[...,tf.newaxis]

<tf.Tensor: shape=(3, 8, 1), dtype=int32, numpy=
array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16]],

       [[17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24]]])>

In [77]:
x[:,:,tf.newaxis]

<tf.Tensor: shape=(3, 8, 1), dtype=int32, numpy=
array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16]],

       [[17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24]]])>

In [78]:
tf.expand_dims(x, axis=-1)

<tf.Tensor: shape=(3, 8, 1), dtype=int32, numpy=
array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16]],

       [[17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24]]])>

In [79]:
# Manipulating tensors

In [80]:
x+10

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34]])>

In [81]:
x*10

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 10,  20,  30,  40,  50,  60,  70,  80],
       [ 90, 100, 110, 120, 130, 140, 150, 160],
       [170, 180, 190, 200, 210, 220, 230, 240]])>

In [82]:
x-10

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[-9, -8, -7, -6, -5, -4, -3, -2],
       [-1,  0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13, 14]])>

In [83]:
x/10

<tf.Tensor: shape=(3, 8), dtype=float64, numpy=
array([[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8],
       [0.9, 1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6],
       [1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4]])>

In [84]:
x//10

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 2, 2, 2, 2, 2]])>

In [85]:
x%2

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])>

In [87]:
tf.multiply(x,10) #much more faster

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 10,  20,  30,  40,  50,  60,  70,  80],
       [ 90, 100, 110, 120, 130, 140, 150, 160],
       [170, 180, 190, 200, 210, 220, 230, 240]])>

In [89]:
y = tf.constant(numpyA, shape=(8,3))

In [90]:
tf.matmul(x,y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 540,  576,  612],
       [1276, 1376, 1476],
       [2012, 2176, 2340]])>

In [91]:
tf.matmul(y,x)

<tf.Tensor: shape=(8, 8), dtype=int32, numpy=
array([[  70,   76,   82,   88,   94,  100,  106,  112],
       [ 151,  166,  181,  196,  211,  226,  241,  256],
       [ 232,  256,  280,  304,  328,  352,  376,  400],
       [ 313,  346,  379,  412,  445,  478,  511,  544],
       [ 394,  436,  478,  520,  562,  604,  646,  688],
       [ 475,  526,  577,  628,  679,  730,  781,  832],
       [ 556,  616,  676,  736,  796,  856,  916,  976],
       [ 637,  706,  775,  844,  913,  982, 1051, 1120]])>

In [92]:
x@y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 540,  576,  612],
       [1276, 1376, 1476],
       [2012, 2176, 2340]])>

In [93]:
tf.transpose(x)

<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23],
       [ 8, 16, 24]])>

In [94]:
tf.reshape(x, shape=(8,3))

<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])>

In [96]:
x

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])>

In [97]:
# Changing the datatypes of a tensor

In [99]:
x.dtype

tf.int32

In [103]:
y = tf.cast(x, dtype=tf.float16)
y.dtype

tf.float16

In [104]:
# Aggregating tensors

In [105]:
tf.abs(x)

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])>

In [110]:
tf.reduce_max(x)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [111]:
tf.reduce_min(x)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [112]:
tf.reduce_max(x[0])

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [113]:
tf.reduce_mean(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [114]:
tf.reduce_mean(x[0])

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [115]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=int32, numpy=300>

In [119]:
# !pip install tensorflow_probability
import tensorflow_probability as tfp

In [121]:
tf.math.reduce_std(tf.cast(x,dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=6.91>

In [128]:
tfp.stats.stddev(tf.cast(tf.reshape(x,shape=(1,24)),dtype=tf.float16))

<tf.Tensor: shape=(24,), dtype=float16, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.], dtype=float16)>

In [129]:
tf.reduce_max(x[:,0])

<tf.Tensor: shape=(), dtype=int32, numpy=17>

In [130]:
x

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])>

In [131]:
tf.argmax(x) # index of max value for each column

<tf.Tensor: shape=(8,), dtype=int64, numpy=array([2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)>

In [139]:
tf.gather(x,tf.argmax(x))[0]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([17, 18, 19, 20, 21, 22, 23, 24])>

In [147]:
x = tf.constant(tf.random.uniform(shape=(5,4)))
x

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.95831835, 0.01680839, 0.3156035 , 0.16013157],
       [0.7148702 , 0.7892921 , 0.11484027, 0.33310425],
       [0.21091413, 0.62329304, 0.9865029 , 0.12230623],
       [0.20660043, 0.87113273, 0.0206511 , 0.21824265],
       [0.6902214 , 0.70987105, 0.8787489 , 0.4835763 ]], dtype=float32)>

In [154]:
y = tf.gather(x,tf.argmax(x))

In [159]:
y

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.95831835, 0.01680839, 0.3156035 , 0.16013157],
       [0.20660043, 0.87113273, 0.0206511 , 0.21824265],
       [0.21091413, 0.62329304, 0.9865029 , 0.12230623],
       [0.6902214 , 0.70987105, 0.8787489 , 0.4835763 ]], dtype=float32)>

In [160]:
tf.linalg.tensor_diag_part(y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.95831835, 0.87113273, 0.9865029 , 0.4835763 ], dtype=float32)>

In [161]:
# One hoting encoding

In [166]:
tf.one_hot(tf.constant([1,2,3,2,2,1]), depth=4)

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.]], dtype=float32)>

In [167]:
# Check phisical devices

In [168]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [169]:
!nvidia-smi

'nvidia-smi' nÆo ‚ reconhecido como um comando interno
ou externo, um programa oper vel ou um arquivo em lotes.
